language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install pytest --upgrade
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest -rAsq
