dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest -rAsq --reruns 10 --reruns-delay 1
